/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import java.util.*;
import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class AAstAvalie extends PAstAvalie
{
    private PExpGeral _expGeral_;
    private final LinkedList<PAstCaso> _astCaso_ = new LinkedList<PAstCaso>();
    private PAstSenaoAvalie _astSenaoAvalie_;

    public AAstAvalie()
    {
        // Constructor
    }

    public AAstAvalie(
        @SuppressWarnings("hiding") PExpGeral _expGeral_,
        @SuppressWarnings("hiding") List<?> _astCaso_,
        @SuppressWarnings("hiding") PAstSenaoAvalie _astSenaoAvalie_)
    {
        // Constructor
        setExpGeral(_expGeral_);

        setAstCaso(_astCaso_);

        setAstSenaoAvalie(_astSenaoAvalie_);

    }

    @Override
    public Object clone()
    {
        return new AAstAvalie(
            cloneNode(this._expGeral_),
            cloneList(this._astCaso_),
            cloneNode(this._astSenaoAvalie_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAstAvalie(this);
    }

    public PExpGeral getExpGeral()
    {
        return this._expGeral_;
    }

    public void setExpGeral(PExpGeral node)
    {
        if(this._expGeral_ != null)
        {
            this._expGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGeral_ = node;
    }

    public LinkedList<PAstCaso> getAstCaso()
    {
        return this._astCaso_;
    }

    public void setAstCaso(List<?> list)
    {
        for(PAstCaso e : this._astCaso_)
        {
            e.parent(null);
        }
        this._astCaso_.clear();

        for(Object obj_e : list)
        {
            PAstCaso e = (PAstCaso) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._astCaso_.add(e);
        }
    }

    public PAstSenaoAvalie getAstSenaoAvalie()
    {
        return this._astSenaoAvalie_;
    }

    public void setAstSenaoAvalie(PAstSenaoAvalie node)
    {
        if(this._astSenaoAvalie_ != null)
        {
            this._astSenaoAvalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astSenaoAvalie_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expGeral_)
            + toString(this._astCaso_)
            + toString(this._astSenaoAvalie_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expGeral_ == child)
        {
            this._expGeral_ = null;
            return;
        }

        if(this._astCaso_.remove(child))
        {
            return;
        }

        if(this._astSenaoAvalie_ == child)
        {
            this._astSenaoAvalie_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expGeral_ == oldChild)
        {
            setExpGeral((PExpGeral) newChild);
            return;
        }

        for(ListIterator<PAstCaso> i = this._astCaso_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAstCaso) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._astSenaoAvalie_ == oldChild)
        {
            setAstSenaoAvalie((PAstSenaoAvalie) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
