/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class ACompostaAstVarvirgula extends PAstVarvirgula
{
    private PAstVarDef _astVarDef_;
    private TVirgula _virgula_;
    private PAstVarvirgula _astVarvirgula_;

    public ACompostaAstVarvirgula()
    {
        // Constructor
    }

    public ACompostaAstVarvirgula(
        @SuppressWarnings("hiding") PAstVarDef _astVarDef_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PAstVarvirgula _astVarvirgula_)
    {
        // Constructor
        setAstVarDef(_astVarDef_);

        setVirgula(_virgula_);

        setAstVarvirgula(_astVarvirgula_);

    }

    @Override
    public Object clone()
    {
        return new ACompostaAstVarvirgula(
            cloneNode(this._astVarDef_),
            cloneNode(this._virgula_),
            cloneNode(this._astVarvirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompostaAstVarvirgula(this);
    }

    public PAstVarDef getAstVarDef()
    {
        return this._astVarDef_;
    }

    public void setAstVarDef(PAstVarDef node)
    {
        if(this._astVarDef_ != null)
        {
            this._astVarDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astVarDef_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PAstVarvirgula getAstVarvirgula()
    {
        return this._astVarvirgula_;
    }

    public void setAstVarvirgula(PAstVarvirgula node)
    {
        if(this._astVarvirgula_ != null)
        {
            this._astVarvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astVarvirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astVarDef_)
            + toString(this._virgula_)
            + toString(this._astVarvirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astVarDef_ == child)
        {
            this._astVarDef_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._astVarvirgula_ == child)
        {
            this._astVarvirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astVarDef_ == oldChild)
        {
            setAstVarDef((PAstVarDef) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._astVarvirgula_ == oldChild)
        {
            setAstVarvirgula((PAstVarvirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
