/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import java.util.*;
import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaConjComandos extends PConjComandos
{
    private final LinkedList<PConjComandos> _conjComandos_ = new LinkedList<PConjComandos>();
    private PAstLeia _astLeia_;

    public ALeiaConjComandos()
    {
        // Constructor
    }

    public ALeiaConjComandos(
        @SuppressWarnings("hiding") List<?> _conjComandos_,
        @SuppressWarnings("hiding") PAstLeia _astLeia_)
    {
        // Constructor
        setConjComandos(_conjComandos_);

        setAstLeia(_astLeia_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaConjComandos(
            cloneList(this._conjComandos_),
            cloneNode(this._astLeia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaConjComandos(this);
    }

    public LinkedList<PConjComandos> getConjComandos()
    {
        return this._conjComandos_;
    }

    public void setConjComandos(List<?> list)
    {
        for(PConjComandos e : this._conjComandos_)
        {
            e.parent(null);
        }
        this._conjComandos_.clear();

        for(Object obj_e : list)
        {
            PConjComandos e = (PConjComandos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._conjComandos_.add(e);
        }
    }

    public PAstLeia getAstLeia()
    {
        return this._astLeia_;
    }

    public void setAstLeia(PAstLeia node)
    {
        if(this._astLeia_ != null)
        {
            this._astLeia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astLeia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjComandos_)
            + toString(this._astLeia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjComandos_.remove(child))
        {
            return;
        }

        if(this._astLeia_ == child)
        {
            this._astLeia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PConjComandos> i = this._conjComandos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PConjComandos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._astLeia_ == oldChild)
        {
            setAstLeia((PAstLeia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
