/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplasAstDclVarLista extends PAstDclVarLista
{
    private PAstDclVarLista _astDclVarLista_;
    private PAstVarDef _astVarDef_;

    public AMultiplasAstDclVarLista()
    {
        // Constructor
    }

    public AMultiplasAstDclVarLista(
        @SuppressWarnings("hiding") PAstDclVarLista _astDclVarLista_,
        @SuppressWarnings("hiding") PAstVarDef _astVarDef_)
    {
        // Constructor
        setAstDclVarLista(_astDclVarLista_);

        setAstVarDef(_astVarDef_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplasAstDclVarLista(
            cloneNode(this._astDclVarLista_),
            cloneNode(this._astVarDef_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplasAstDclVarLista(this);
    }

    public PAstDclVarLista getAstDclVarLista()
    {
        return this._astDclVarLista_;
    }

    public void setAstDclVarLista(PAstDclVarLista node)
    {
        if(this._astDclVarLista_ != null)
        {
            this._astDclVarLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astDclVarLista_ = node;
    }

    public PAstVarDef getAstVarDef()
    {
        return this._astVarDef_;
    }

    public void setAstVarDef(PAstVarDef node)
    {
        if(this._astVarDef_ != null)
        {
            this._astVarDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astVarDef_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astDclVarLista_)
            + toString(this._astVarDef_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astDclVarLista_ == child)
        {
            this._astDclVarLista_ = null;
            return;
        }

        if(this._astVarDef_ == child)
        {
            this._astVarDef_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astDclVarLista_ == oldChild)
        {
            setAstDclVarLista((PAstDclVarLista) newChild);
            return;
        }

        if(this._astVarDef_ == oldChild)
        {
            setAstVarDef((PAstVarDef) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
