/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class AOubinExpLogica extends PExpLogica
{
    private PExpLogica _esq_;
    private PExpLogica _dir_;

    public AOubinExpLogica()
    {
        // Constructor
    }

    public AOubinExpLogica(
        @SuppressWarnings("hiding") PExpLogica _esq_,
        @SuppressWarnings("hiding") PExpLogica _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AOubinExpLogica(
            cloneNode(this._esq_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOubinExpLogica(this);
    }

    public PExpLogica getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PExpLogica node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PExpLogica getDir()
    {
        return this._dir_;
    }

    public void setDir(PExpLogica node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PExpLogica) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PExpLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
