/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesAstEscreva extends PAstEscreva
{
    private PExpGeral _expGeral_;

    public ASimplesAstEscreva()
    {
        // Constructor
    }

    public ASimplesAstEscreva(
        @SuppressWarnings("hiding") PExpGeral _expGeral_)
    {
        // Constructor
        setExpGeral(_expGeral_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesAstEscreva(
            cloneNode(this._expGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesAstEscreva(this);
    }

    public PExpGeral getExpGeral()
    {
        return this._expGeral_;
    }

    public void setExpGeral(PExpGeral node)
    {
        if(this._expGeral_ != null)
        {
            this._expGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGeral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expGeral_ == child)
        {
            this._expGeral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expGeral_ == oldChild)
        {
            setExpGeral((PExpGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
