/* This file was generated by SableCC (http://www.sablecc.org/). */

package Portugol.node;

import Portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVazioAstDeclaracoes extends PAstDeclaracoes
{

    public AVazioAstDeclaracoes()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioAstDeclaracoes();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioAstDeclaracoes(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
